all:
  children:
    swarm_manager:
      hosts:
        manager:
          ansible_host: 3.147.63.175
          private_ip: 10.0.1.156
    swarm_workers:
      hosts:
        worker1:
          ansible_host: 18.225.95.206
          private_ip: 10.0.1.62
        worker2:
          ansible_host: 52.14.87.50
          private_ip: 10.0.1.235
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ca0-keys.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'